[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
cosmwasm-std = "1.0.0"
cw-storage-plus = "0.13.0"
schemars = "0.8.8"
serde = "1.0.136"

cosmwasm-schema = "1.0"
bincode = "2.0.1"
